# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: CD - Backend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    paths:
      - 'backend/**'
      - '.github/workflows/cd-backend.yml'

defaults:
  run:
    working-directory: backend

jobs:
  build-and-push-docker-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'dev' || 'prod' }}

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Authenticate to GCP
        id: auth
        uses: 'google-github-actions/auth@v3'
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCP_SNAMPO_WIP_ID }}
          service_account: ${{ vars.GCP_SNAMPO_CICD_SA}}

      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: asia-northeast1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.GAR_REPOSITORY }}/snampo-be
          tags: |
            type=semver,pattern={{version}}
            type=raw,value={{date 'YYYYMMDDHH' tz='Asia/Tokyo'}}-{{branch}}-{{sha}}

      - name: Build and Push Docker image to GAR
        id: docker_build_push
        uses: docker/build-push-action@v6
        with:
          context: backend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

    outputs:
      image_tag: ${{ fromJSON(steps.meta.outputs.json).tags[0] }}

  deploy-to-cloud-run:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    environment: ${{ github.ref_name == 'main' && 'dev' || 'prod' }}

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Authenticate to GCP
        uses: 'google-github-actions/auth@v3'
        with:
          workload_identity_provider: ${{ secrets.GCP_SNAMPO_WIP_ID }}
          service_account: ${{ vars.GCP_SNAMPO_CICD_SA}}

      - name: Deploy to Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v3'
        with:
          service: ${{ vars.SNAMPO_SERVICE }}
          image: ${{ needs.build-and-push-docker-image.outputs.image_tag }}
          region: 'asia-northeast1'
