# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Terraform Diff Check

on:
  workflow_call:
    inputs:
      source_ref:
        required: true
        type: string
        description: 比較元のブランチまたはコミット
      target_ref:
        required: true
        type: string
        description: 比較先のブランチまたはコミット

    outputs:
      environments:
        description: 差分がある環境
        value: ${{ jobs.check-diff.outputs.environments }}

jobs:
  check-diff:
    name: Terraform Diff Check
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.check-diff.outputs.envs }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Check diff
        id: check-diff
        run: |
          dir=('../modules' 'dev' 'prod')

          # 変更がある環境を判定
          declare -A flag=(["dev"]=0 ["prod"]=0)
          for d in "${dir[@]}"; do
            diff=$(git diff --name-only ${{ inputs.source_ref }} ${{ inputs.target_ref }} -- terraform/env/$d/)
            if [[ -n "$diff" && $d == "../modules" ]] ; then
              echo "Changes detected in terraform/env/$d/"
              flag[dev]=1
              flag[prod]=1
            elif [[ -n "$diff" && $d != "modules" ]] ; then
              echo "Changes detected in terraform/env/$d/"
              flag[$d]=1
            fi
          done

          # 配列を作成
          envs=()
          for key in "${!flag[@]}"; do
            if [[ ${flag[$key]} -eq 1 ]]; then
              envs+=("$key")
            fi
          done

          # 配列の長さが0の場合は終了
          if [ ${#envs[@]} -eq 0 ]; then
            echo "No changes detected in any environment."
            exit 0
          fi
          
          environments=$(jq -cn '$ARGS.positional' --args -- "${envs[@]}")
          echo "envs=$environments" >> $GITHUB_OUTPUT
